version: '3.8'

services:
  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservice-network
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - microservice-network


  api-gateway:
    image: api-gateway
    container_name: api-gateway
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    ports:
      - "9999:8888"
    networks:
      - microservice-network

  department-service:
    build:
      context: ./department-service
    image: department-service
    container_name: department-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - microservice-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/testing_system
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_APPLICATION_NAME: department-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
  account-service:
    build:
      context: ./account-service
    image: account-service
    container_name: account-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - microservice-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/testing_system
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_APPLICATION_NAME: account-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
networks:
  microservice-network:
    driver: bridge

volumes:
  mysql-data:
