version: '3.8'

services:

  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123@abc
      MYSQL_DATABASE: TestingSystem
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123@abc
    ports:
      - "3307:3306"
    networks:
      - microservice-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
  department-service:
    image: department-service:latest
    container_name: department-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/TestingSystem
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123@abc
      SPRING_APPLICATION_NAME: department-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mysql
      - eureka-server
    ports:
      - "8082:8080"
    networks:
      - microservice-network
      
  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    ports:
      - "8089:8080"
    networks:
      - microservice-network    

networks:
  microservice-network:
    driver: bridge

volumes:
  mysql-data:
